function createMPGFigure(X1, Y1)
%CREATEMPGFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

% Auto-generated by MATLAB on 07-Jan-2015 17:37:50
% Copyright 2017 The MathWorks, Inc.

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel('MPG');

% Create xlabel
xlabel('Rated Horsepower');

% Create title
title('Fuel Economy vs. Rated Horsepower');

% Create grid
grid on

% Create plot
plot(X1,Y1,'Marker','pentagram','LineStyle','none');

