function data = importData(yr, dataDir)
% IMPORTYEARXLS  Import fuel economy data (from Excel data files)
%   DATA = IMPORTYEARXLS(YR) imports for the year YR. YR can be a scalar or
%   a vector of years between 2000 and 2007.
%
% Example:
%   data = importYearXLS(2005);
%   data = importYearXLS([2000 2004]);

% Copyright 2017 The MathWorks, Inc.

% Error check input argument
narginchk(1, 2);
validateattributes(yr, {'numeric'}, ...
    {'integer', 'vector', '>=', 2000, '<=', 2012});

if nargin == 1
    % Directory where the data files reside
    dataDir = 'Data';
end

data = table;

% Loop through requested years
for iYear = 1:length(yr)
    
    filename = fullfile(dataDir,[num2str(yr(iYear)),'dat.xlsx']);
    data = [data; importfile(filename)]; %#ok<AGROW>
    
end

data.Km_gal = data.Km_gal*1.60934;
data.Weight = data.Weight*0.453592;

end


function dat = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DAT = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  DAT = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  DAT = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  dat = importfile("C:\work\demos\FuelEconomy\Data\2007dat.xlsx", "Sheet1", [2, 2596]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-May-2020 10:55:11

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 2596];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 24);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":X" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Year", "MfrName", "CarLine", "Car_Truck", "EngDisp", "Police", "RatedHP", "Transmission", "Drive", "Weight", "Comp", "AxleRatio", "EVSpeedRatio", "AC", "PRP", "FuelType", "City_Highway", "HC", "CO", "CO2", "NOX", "Km_gal", "Valves_Cyl", "CoastDownTime"];
opts.VariableTypes = ["double", "categorical", "categorical", "categorical", "double", "categorical", "double", "categorical", "categorical", "double", "double", "double", "double", "categorical", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["MfrName", "CarLine", "Car_Truck", "Police", "Transmission", "Drive", "AC", "City_Highway"], "EmptyFieldRule", "auto");

% Import the data
dat = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":X" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    dat = [dat; tb]; %#ok<AGROW>
end
end